class Beneficiary {
  final int? id, beneficiaryType;
  final String? accountName,
      accountType,
      accountNo,
      bankName,
      bankSortCode,
      bankRoutingNo,
      bankCode,
      cur,
      beneficiaryEmail,
      swift,
      country,
      beneficiaryCountry,
      state,
      bankState,
      stateId,
      address,
      bankAddress,
      zipcode,
      bankZipcode,
      city,
      bankCity,
      mobile;

  Beneficiary({
    this.id,
    this.accountName,
    this.accountNo,
    this.beneficiaryType,
    this.accountType,
    this.bankCode,
    this.bankName,
    this.bankSortCode,
    this.bankRoutingNo,
    this.cur,
    this.beneficiaryEmail,
    this.swift,
    this.country,
    this.beneficiaryCountry,
    this.state,
    this.bankState,
    this.stateId,
    this.address,
    this.bankAddress,
    this.zipcode,
    this.bankZipcode,
    this.city,
    this.bankCity,
    this.mobile,
  });

  static Beneficiary fromMap(Map data) => Beneficiary(
        id: data['id'],
        accountName: data['accountName'],
        accountNo: data['accountNo'],
        beneficiaryType: data['beneficiaryType'],
        accountType: data['accountType'],
        bankCode: data['bankCode'].toString(),
        bankName: data['bankName'],
        bankSortCode: data['bankSortCode'],
        bankRoutingNo: data['bankRoutingNo'],
        city: data['city'],
        bankCity: data['bankCity'],
        country: data['country'],
        beneficiaryCountry: data['beneficiaryCountry'],
        cur: data['cur'],
        beneficiaryEmail: data['beneficiaryEmail'],
        state: data['state'],
        bankState: data['bankState'],
        stateId: data['stateId'],
        swift: data['swift'],
        address: data['address'],
        bankAddress: data['bankAddress'],
        zipcode: data['zipcode'],
        bankZipcode: data['bankZipcode'],
        mobile: data['mobile'],
      );
}
